import { config } from 'dotenv';

config();

const APP_NAME_PREFIX = process.env.APP_NAME.toUpperCase();

export const CACHE_CONSTANT = {
  SESSION_PREFIX: `${APP_NAME_PREFIX}:SESSION_USERID:`,
  SESSION_EMAIL_PREFIX: `${APP_NAME_PREFIX}:EMAIL_USERID:`,
  SESSION_EMAIL_ADMIN_PREFIX: `${APP_NAME_PREFIX}:EMAIL_ADMINID:`,
  ACCESS_TOKEN_PREFIX: `${APP_NAME_PREFIX}:ACCESS_TOKEN:`,
  REFRESH_TOKEN_PREFIX: `${APP_NAME_PREFIX}:REFRESH_TOKEN:`,
  ACCESS_TOKEN_ADMIN_PREFIX: `${APP_NAME_PREFIX}:ACCESS_TOKEN_ADMIN:`,
  REFRESH_TOKEN_ADMIN_PREFIX: `${APP_NAME_PREFIX}:REFRESH_TOKEN_ADMIN:`,
  USER_SIGNATURE_MESSAGE_PREFIX: `${APP_NAME_PREFIX}:USER_SIGNATURE:`,
};
