import { config } from 'dotenv';
import type { IContract } from 'src/shared/interfaces/contract.interface';

config();

export const PAYMENT: IContract = {
  Address: process.env.PAYMENT_CONTRACT_ADDRESS,
  ABI: [
    { inputs: [{ internalType: 'address', name: 'target', type: 'address' }], name: 'AddressEmptyCode', type: 'error' },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'AddressInsufficientBalance',
      type: 'error',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'uint256', name: 'maximum', type: 'uint256' },
      ],
      name: 'AmountHigherThanMaximum',
      type: 'error',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'uint256', name: 'minimum', type: 'uint256' },
      ],
      name: 'AmountLowerThanMinimum',
      type: 'error',
    },
    { inputs: [], name: 'ContractIsPaused', type: 'error' },
    { inputs: [], name: 'ContractPaused', type: 'error' },
    { inputs: [], name: 'ECDSAInvalidSignature', type: 'error' },
    {
      inputs: [{ internalType: 'uint256', name: 'length', type: 'uint256' }],
      name: 'ECDSAInvalidSignatureLength',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'bytes32', name: 's', type: 'bytes32' }],
      name: 'ECDSAInvalidSignatureS',
      type: 'error',
    },
    { inputs: [], name: 'FailedInnerCall', type: 'error' },
    { inputs: [], name: 'InvalidAddress', type: 'error' },
    { inputs: [], name: 'InvalidInitialization', type: 'error' },
    {
      inputs: [{ internalType: 'uint256', name: 'newMaximumWithdraw', type: 'uint256' }],
      name: 'InvalidMaximumWithdraw',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'newMinimumWithdraw', type: 'uint256' }],
      name: 'InvalidMinimumWithdraw',
      type: 'error',
    },
    { inputs: [{ internalType: 'uint256', name: 'rate', type: 'uint256' }], name: 'InvalidRate', type: 'error' },
    { inputs: [{ internalType: 'bytes', name: 'signature', type: 'bytes' }], name: 'InvalidSignature', type: 'error' },
    { inputs: [], name: 'NotInitializing', type: 'error' },
    {
      inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
      name: 'OwnableInvalidOwner',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'OwnableUnauthorizedAccount',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
      name: 'SafeERC20FailedOperation',
      type: 'error',
    },
    { inputs: [], name: 'TransactionTimeout', type: 'error' },
    { inputs: [], name: 'TransferFail', type: 'error' },
    {
      inputs: [{ internalType: 'uint256', name: 'withdrawRequestId', type: 'uint256' }],
      name: 'WithdrawRequestHasExecuted',
      type: 'error',
    },
    { inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }], name: 'ZeroAmount', type: 'error' },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'newBurnRate', type: 'uint256' }],
      name: 'BurnRateChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'bool', name: 'paused', type: 'bool' }],
      name: 'ContractSetPause',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'from', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'transferAmount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'burnAmount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'stakingAmount', type: 'uint256' },
      ],
      name: 'Deposit',
      type: 'event',
    },
    { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'newFeeRate', type: 'uint256' }],
      name: 'FeeRateChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'address', name: 'newFeeWallet', type: 'address' }],
      name: 'FeeWalletChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
      name: 'Initialized',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'newMaximumWithdraw', type: 'uint256' }],
      name: 'MaximumWithdrawChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'newMinimumWithdraw', type: 'uint256' }],
      name: 'MinimumWithdrawChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
        { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
      ],
      name: 'OwnershipTransferred',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'address', name: 'GPUMarketPlaceAddress', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      ],
      name: 'PayForGPUMarketPlace',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'newStakingRate', type: 'uint256' }],
      name: 'StakingRateChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'address', name: 'newStakingWallet', type: 'address' }],
      name: 'StakingWalletChange',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'to', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'transferAmount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'feeAmount', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'withdrawRequestId', type: 'uint256' },
      ],
      name: 'Withdraw',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'address', name: 'newWithdrawSigner', type: 'address' }],
      name: 'WithdrawSignerChange',
      type: 'event',
    },
    {
      inputs: [],
      name: 'BURN_ADDRESS',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'PERCENT_DENOMINATOR',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'WITHDRAW_TYPE_HASH',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'burnRate',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    { inputs: [], name: 'deposit', outputs: [], stateMutability: 'payable', type: 'function' },
    {
      inputs: [],
      name: 'eip712Domain',
      outputs: [
        { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
        { internalType: 'string', name: 'name', type: 'string' },
        { internalType: 'string', name: 'version', type: 'string' },
        { internalType: 'uint256', name: 'chainId', type: 'uint256' },
        { internalType: 'address', name: 'verifyingContract', type: 'address' },
        { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
        { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'token', type: 'address' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
      ],
      name: 'emergencyWithdraw',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'feeRate',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'feeWallet',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'initialOwner', type: 'address' },
        { internalType: 'address', name: 'initialFeeWallet', type: 'address' },
        { internalType: 'address', name: 'initialStakingWallet', type: 'address' },
        { internalType: 'address', name: 'initWithdrawSigner', type: 'address' },
        { internalType: 'string', name: '_initName', type: 'string' },
        { internalType: 'string', name: '_initVersion', type: 'string' },
      ],
      name: 'initialize',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'isPaused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'maximumWithdraw',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'minimumWithdraw',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
      inputs: [{ internalType: 'uint256', name: 'newBurnRate', type: 'uint256' }],
      name: 'setBurnRate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'newFeeRate', type: 'uint256' }],
      name: 'setFeeRate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newFeeWallet', type: 'address' }],
      name: 'setFeeWallet',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'newMaximumWithdraw', type: 'uint256' }],
      name: 'setMaximumWithdraw',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'newMinimumWithdraw', type: 'uint256' }],
      name: 'setMinimumWithdraw',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bool', name: 'paused', type: 'bool' }],
      name: 'setPaused',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'newStakingRate', type: 'uint256' }],
      name: 'setStakingRate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newStakingWallet', type: 'address' }],
      name: 'setStakingWallet',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newWithdrawSigner', type: 'address' }],
      name: 'setWithdrawSigner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'stakingRate',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'stakingWallet',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'to', type: 'address' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'uint256', name: 'withdrawRequestId', type: 'uint256' },
        { internalType: 'uint256', name: 'withdrawRequestTimestamp', type: 'uint256' },
        { internalType: 'bytes', name: 'signature', type: 'bytes' },
      ],
      name: 'withdraw',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'withdrawRequestId', type: 'uint256' }],
      name: 'withdrawRequestStatus',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'withdrawSigner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
  ],
};
